# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: kn1kn1.github.io
description: > # this means to ignore newlines until "baseurl:"
twitter_username: kn1kn1
github_username:  kn1kn1

# Build settings
markdown: kramdown

# Github pages settings
github: [metadata]
kramdown:
 input: GFM
 hard_wrap: false
gems:
 - jekyll-coffeescript
 - jekyll-paginate

timezone: Asia/Tokyo
future: true
